source 'https://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3'
gem 'sinatra'
gem 'thin'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'rake'
gem 'require_all'

gem 'rgl' , require: ['rgl/adjacency','rgl/dot', 'rgl/implicit']

# require 'rgl/adjacency'
# require 'rgl/dot'
# require 'rgl/implicit'

# gem 'rspec'
# gem 'rack-test'
# gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
# gem 'capybara'
